### PR TITLE
Changing proj API from v4 to v6

### PR DESCRIPTION
**Pull request by cyper85**
https://github.com/osmcode/libosmium/issues/277

### CODE REVIEW

**Comment by cyper85** [comment]
https://git.neumann-andreas.de/andreas/libosmium-docker/blob/master/Dockerfile

Test-Docker-Build-Container with alpine:latest and proj v6

**Comment by joto** [comment]
Thanks for the pull request. Please check what happened that all lines show up as changed. Also for backwards compatibility the old API must still work, please add some kind of ifdef-magic or so to check for that.

**Comment by Nakaner** [comment]
> Also for backwards compatibility the old API must still work, please add some kind of ifdef-magic or so to check for that.

@cyper85 You might have a look at https://github.com/Nakaner/osmium-geos-factory/blob/master/include/osmium_geos_factory/geos_factory.hpp#L47 where I deal with changes in GEOS's C++ API. `proj.h` defines the macros `PROJ_VERSION_MAJOR`, `PROJ_VERSION_MINOR` and `PROJ_VERSION_MAJOR` patch for that purpose.

**Comment by joto** [comment]
* It still shows all lines as changed. Is there a problem with line endings?
* `__has_include` is only available since C++17, but libosmium should work from C++11 on.

**Comment by cyper85** [comment]
Okay,

I had to modify .trafis.yml. Due the little Change I add osx10.2 and osx11 to the installation.

In osx will build proj in v6.1, so you can see in your tests, that it works.

**Comment by joto** [comment]
We have a temporary solution (see #277) now.

This patch is problematic on several levels. Some problems I have mentioned above. Then there is the use of `const_cast`. And even if we solve all this, the API that libosmium provides just can't be implemented suitably with the new proj API. We need a better solution.

**Pull request closed without merging**
