### PR TITLE
Explicitly export exception types.

### PR DESCRIPTION
**Pull request by oraluben**
This should fix osmcode/pyosmium#165

Ref: pybind/pybind11#2999, [GCC Wiki](https://gcc.gnu.org/wiki/Visibility)

### CODE REVIEW

**Comment by oraluben** [comment]
Working on CI failure.

**Comment by joto** [comment]
Looks to me like you probably didn't include the `compatibility.hpp` everywhere that's needed. For instance in `include/osmium/memory/buffer.hpp`.

**Comment by oraluben** [comment]
> Looks to me like you probably didn't include the `compatibility.hpp` everywhere that's needed. For instance in `include/osmium/memory/buffer.hpp`.

Thanks for your reply! They already included the file (e.g. [in `buffer.hpp`](https://github.com/osmcode/libosmium/blob/master/include/osmium/memory/buffer.hpp#L39)), and I also successfully compiled the project. Is there anything different I should notice between local and the CI's environment?

**Comment by joto** [comment]
I have merged this now (in slightly different form). Sorry it took so long, but I needed to understand what's happening here first.

**Comment by joto** [comment]
Because VS is generating warnings I wrapped the code defining `OSMIUM_EXPORT` into an `#ifdef OSMIUM_DEFINE_EXPORT`. So you have to compile with `-DOSMIUM_DEFINE_EXPORT` if you need this functionality. Can you provide a PR for Pyosmium if that works for you?

**Comment by oraluben** [comment]
@joto thanks! I'll try to draft a PR there.

**Pull request closed without merging**
