### PR TITLE
Check for bad file descriptors when opening bzip2-compressed files

### PR DESCRIPTION
**Pull request by brawer**
After this change, all tests pass on Alpine Linux.
Fixes https://github.com/osmcode/libosmium/issues/353.

### CODE REVIEW

**Comment by brawer** [comment]
The AppVeyor build failure seems unrelated to the change.
https://github.com/osmcode/libosmium/issues/355

**Comment by joto** [comment]
Fails on Windows builds.

**Comment by brawer** [comment]
> Fails on Windows builds.

@joto, mind approving running GitHub workflows for this change? Should be fixed on Windows, but as a first-time committer to this repo, I can’t start the workflow myself.

**Comment by joto** [comment]
I am not too happy about that solution. Having to fix a minor problem that will never show up in real use on a fringe system is bad enough and now we need a fix for the fix (ie the ifdef) because it doesn't work on Windows. Maybe we need a different approach here. Presumably using a broken file descriptor with musl will still fail, but instead of in the fdopen somewhere down the line when we try to read some data. Maybe the test should be rewritten to accept failure then.

**Comment by brawer** [comment]
Agree. See https://github.com/osmcode/libosmium/pull/357 for an alternative fix.

**Pull request closed without merging**
